
try {
console.log('program ran ssuccessfully',p);
return;
}catch(err){

    console.log(program);
}

// final will run regardless of any errors or termination in the code 
finally
{
    console.log('I am finally');
}